name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: ko-build/setup-ko@v0.8
      - run: ko publish -B ./cmd/tracefs-exporter/ --tags latest,$RELEASE_VERSION
